paginate: 5
pygments: true
permalink: /:year/:month/:day/:title/
markdown: kramdown
name: Justin Howard Wilson's blog
description: A blog about general physics, condensed matter physics, mathematical physics, and sometimes pure math with digressions into writing style, LaTeX, presentation style, and other tools for research. Expect lots of math and digressions into writing style, LaTeX, presentation style, and other tools for research.
url: http://jhwilson.com