gems: [jekyll-paginate]
paginate: 5
highlighter: pygments
permalink: /:year/:month/:day/:title/
markdown: kramdown
name: Justin Howard Wilson's blog
description: A blog about general physics, condensed matter physics, mathematical physics, and sometimes pure math with digressions into writing style, LaTeX, presentation style, and other tools for research. Expect lots of math. (&hstrok;=c=1 unless otherwise stated)
url: http://jhwilson.com